import {StadiumAudio} from './sound.js?v=stadium-audio-1';
const audio=new StadiumAudio();
import {playerPool,availableTeams,playerDetails} from './pools.js?v=stadium-audio-1';
let dataset;
import {createGame,guess,bodyParts} from './game.js?v=stadium-audio-1';
const $=id=>document.getElementById(id);
let stats={wins:0,streak:0,best:0};try{const s=JSON.parse(localStorage.getItem('ice-time-stats'));if(s)for(const k of Object.keys(stats))if(Number.isSafeInteger(s[k])&&s[k]>=0)stats[k]=s[k];}catch{}
let game,bag=[],round=0,lastName='',settled=false,playerId;
function save(){try{localStorage.setItem('ice-time-stats',JSON.stringify(stats));}catch{} }
function pool(){return [...new Set(playerPool(dataset,$('decade').value,$('team').value).map(id=>dataset.players[id]))];}
function refill(){bag=[...pool()];for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]];}if(bag.at(-1)===lastName&&bag.length>1)[bag[0],bag[bag.length-1]]=[bag.at(-1),bag[0]];}
function next(){if(!bag.length)refill();lastName=bag.pop();playerId=playerPool(dataset,$('decade').value,$('team').value).find(id=>dataset.players[id]===lastName);game=createGame(lastName);round++;settled=false;if(audio.enabled)audio.organ(0);render();}
function settle(){if(settled||game.status==='playing')return;settled=true;if(game.status==='won'){stats.wins++;stats.streak++;stats.best=Math.max(stats.best,stats.streak);}else stats.streak=0;save();}
function render(){settle();for(const k of Object.keys(stats))$(k).textContent=String(stats[k]).padStart(2,'0');$('round').textContent=`FACEOFF ${String(round).padStart(2,'0')}`;$('chances').textContent=`${6+Number(game.bonus)-game.misses} MISSES LEFT`;$('bonus').textContent=game.bonus?'✦ BONUS MISS EARNED':`✦ HAT TRICK: ${Math.min(3,game.run)} / 3`;
 const n=$('name');n.replaceChildren();for(const word of game.name.split(' ')){const w=document.createElement('div');w.className='word';w.style.setProperty('--letter-count',word.length);for(const c of word){const el=document.createElement('span');const letter=/[A-Z]/.test(c);const known=game.guessed.includes(c);el.className='letter'+(!letter?' punctuation':'')+(game.status==='lost'&&!known?' reveal':'');el.textContent=(!letter||known||game.status!=='playing')?c:'';el.setAttribute('aria-label',el.textContent||'Blank letter');w.append(el);}n.append(w);}
 const parts=bodyParts(game);document.querySelectorAll('[data-part]').forEach(el=>el.classList.toggle('shown',Number(el.dataset.part)<=parts));$('drawing').setAttribute('aria-label',`Gallows with ${parts} of 6 body parts`);
 document.querySelectorAll('.key').forEach(el=>{const used=game.guessed.includes(el.textContent);el.disabled=used||game.status!=='playing';el.className='key'+(used?(game.name.includes(el.textContent)?' hit':' miss'):'');});
 $('message').textContent=game.status==='won'?`GOAL! ${lastName}. Nicely played.`:game.status==='lost'?`Final whistle. It was ${lastName}.`:game.bonus?'Hat trick! You have one extra miss.':game.misses?'Stay in the game. Pick your next letter.':'Pick a letter. Drop the puck.';
 renderReveal();
 $('next').hidden=game.status==='playing';$('skip').hidden=game.status!=='playing';$('roster-count').textContent=`${pool().length.toLocaleString()} PLAYERS`;$('skip').disabled=false;const current=$('decade').value==='current';$('data-note').textContent=current?`Current roster snapshot: ${dataset.updated}. Refreshed daily.`:`Regular-season appearances · Season start year · Records updated ${dataset.updated}`;}
function renderReveal(){const card=$('reveal');card.hidden=game.status==='playing';$('reveal-details').replaceChildren();if(card.hidden)return;const d=$('decade').value;$('reveal-context').textContent=d==='current'?`Current roster · ${dataset.updated}`:d==='all'?'NHL career records':`${d}s · Regular-season records`;for(const detail of playerDetails(dataset,playerId,d,$('team').value)){const row=document.createElement('div');const team=document.createElement('dt');const position=document.createElement('dd');team.textContent=detail.team;position.textContent=detail.positions.join(' / ');row.append(team,position);$('reveal-details').append(row);}}
function chooseLetter(letter){if(!game)return;const previous=game;audio.unlock();game=guess(game,letter);if(game===previous)return;if(game.status!=='playing')audio.result(game.status==='won');else if(game.misses!==previous.misses||!audio.timer)audio.organ(game.misses);render();}
document.querySelectorAll('.key').forEach(b=>{b.onclick=()=>chooseLetter(b.textContent);});
document.addEventListener('keydown',e=>{if(!game||$('rules').open||e.ctrlKey||e.metaKey||e.altKey||e.target.matches('select,input,textarea'))return;if(/^[a-z]$/i.test(e.key)){chooseLetter(e.key);}});
function filterChange(){if(game?.status==='playing'&&game.guessed.length){game.status='lost';settle();}bag=[];next();}
function teamOptions(){const previous=$('team').value;const ids=availableTeams(dataset,$('decade').value);$('team').replaceChildren(new Option('All teams','all'));for(const id of ids){const t=dataset.teams[id];const historic=!dataset.pools.current[id];$('team').add(new Option(t.name+(historic?' (historical)':''),id));}$('team').value=ids.includes(previous)?previous:'all';}
$('next').onclick=next;$('skip').onclick=()=>{game={...game,status:'lost',misses:6+Number(game.bonus)};audio.result(false);render();};
$('decade').onchange=()=>{teamOptions();filterChange();};$('team').onchange=filterChange;
$('help').onclick=()=>$('rules').showModal();$('reset').onclick=()=>{if(confirm('Reset your wins, streak, and best streak?')){stats={wins:0,streak:0,best:0};save();if(game)render();}};
async function load(){$('message').textContent='Loading NHL records…';$('next').hidden=true;$('decade').disabled=true;$('team').disabled=true;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch('./data/rosters.json',{cache:'no-store',signal:controller.signal});if(!response.ok)throw new Error('Roster fetch failed');dataset=await response.json();if(!dataset.positions?.current||!dataset.pools.current||!Object.keys(dataset.players).length)throw new Error('Invalid roster data');$('decade').replaceChildren(new Option('All decades','all'),new Option('Current roster','current'));for(const d of Object.keys(dataset.pools).filter(d=>d!=='current').sort((a,b)=>b-a))$('decade').add(new Option(d+'s',d));$('decade').value='all';teamOptions();$('decade').disabled=false;$('team').disabled=false;$('next').textContent='Next faceoff →';$('next').onclick=next;next();}catch(error){console.error(error);$('message').textContent='NHL records could not load. Check your connection and try again.';$('next').hidden=false;$('next').textContent='Retry loading records';$('next').onclick=load;}finally{clearTimeout(timeout);}}
$('sound').onclick=()=>{const enabled=audio.setEnabled(!audio.enabled);$('sound').setAttribute('aria-pressed',String(enabled));$('sound').setAttribute('aria-label',enabled?'Turn sound off':'Turn sound on');$('sound').title=enabled?'Sound on':'Sound off';$('sound').querySelector('.sound-slash').hidden=enabled;$('sound').querySelector('.sound-waves').hidden=!enabled;if(enabled&&game?.status==='playing')audio.organ(game.misses);};
document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.stop();else if(audio.enabled&&game?.status==='playing')audio.organ(game.misses);});
window.addEventListener('pagehide',()=>audio.stop());
load();
