// Original stadium-style sounds, synthesized locally. No recordings or network audio.
export class StadiumAudio {
 constructor(){this.enabled=false;this.context=null;this.master=null;this.nodes=new Set();this.timer=null;this.generation=0;this.misses=0;}
 unlock(){if(!this.enabled)return;const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Audio)return;try{if(!this.context){this.context=new Audio();this.master=this.context.createGain();this.master.gain.value=.45;this.master.connect(this.context.destination);}if(this.context.state==='suspended')this.context.resume().catch(()=>{});}catch{this.enabled=false;}}
 setEnabled(enabled){this.enabled=enabled;if(enabled)this.unlock();else this.stop();return this.enabled;}
 stop(){this.generation++;clearTimeout(this.timer);this.timer=null;if(this.context)for(const node of this.nodes){try{node.stop(this.context.currentTime);}catch{}}this.nodes.clear();}
 tone(frequency,start,duration,volume,type='triangle',endFrequency){const ctx=this.context;if(!ctx)return;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,start);if(endFrequency)osc.frequency.exponentialRampToValueAtTime(endFrequency,start+duration);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(volume,start+.02);gain.gain.setValueAtTime(volume*.8,start+Math.max(.03,duration-.08));gain.gain.linearRampToValueAtTime(0,start+duration);osc.connect(gain);gain.connect(this.master);this.nodes.add(osc);osc.onended=()=>{this.nodes.delete(osc);osc.disconnect();gain.disconnect();};osc.start(start);osc.stop(start+duration+.02);}
 organ(misses=0){if(!this.enabled)return;this.unlock();if(!this.context)return;this.stop();this.misses=misses;const generation=this.generation;const beat=60/(88+misses*9)/2;const root=196*2**(misses/12);const riff=[0,4,7,12,9,7,4,7];let step=0;const tick=()=>{if(generation!==this.generation||!this.enabled||globalThis.document?.hidden)return;const time=this.context.currentTime+.015;const frequency=root*2**(riff[step%riff.length]/12);this.tone(frequency,time,beat*.9,.035);this.tone(frequency*2,time,beat*.9,.018,'sine');this.tone(frequency*4,time,beat*.85,.007,'sine');step++;this.timer=setTimeout(tick,beat*1000);};tick();}
 crowd(start,duration,cheering){const ctx=this.context;const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate);const samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1);const source=ctx.createBufferSource();source.buffer=buffer;const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=cheering?1300:450;filter.Q.value=.6;const gain=ctx.createGain();gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(cheering?.07:.035,start+.22);gain.gain.linearRampToValueAtTime(0,start+duration);source.connect(filter);filter.connect(gain);gain.connect(this.master);this.nodes.add(source);source.onended=()=>{this.nodes.delete(source);source.disconnect();filter.disconnect();gain.disconnect();};source.start(start);source.stop(start+duration);
  if(cheering){for(let i=0;i<8;i++){const t=start+i*.22;this.tone(1000+Math.random()*1000,t,.23,.012,'sine',1500+Math.random()*1000);}}else{for(let i=0;i<6;i++)this.tone(125+i*8,start+i*.04,duration-.3,.008,'sawtooth',95+i*5);}}
 result(won){if(!this.enabled)return;this.unlock();if(!this.context)return;this.stop();const time=this.context.currentTime+.025;if(won){const notes=[0,4,7,9,7,12];const lengths=[.16,.16,.16,.24,.13,.52];let offset=0;for(let i=0;i<notes.length;i++){const f=392*2**(notes[i]/12);this.tone(f,time+offset,lengths[i],.055,'sawtooth');this.tone(f/2,time+offset,lengths[i],.018,'triangle');offset+=lengths[i];}this.crowd(time+.8,2.1,true);}else{this.tone(110,time,.85,.065,'square');this.tone(55,time,.85,.025,'triangle');this.crowd(time+.6,1.9,false);}}
}
